### PR TITLE
added a thumbnail auto creation, image resizing to allowed aspect rat…

### PR DESCRIPTION
**Pull request by Julioocz**
…ios and getImageSize replaced with a pillow functionality

### CODE REVIEW

**Comment by LevPasha** [comment]
@Julioocz good work. Please add to readme how to install PIL. And maybee use it only if user need Video\Photo upload?

**Comment by abdulla-alajmi** [comment]
@Julioocz it's not working,  I tried to upload a video and it gives me the statues is ok but no video being uploaded!

**Comment by Julioocz** [comment]
@abdulla-alajmi it's working for me, but i fixed something that may cause a failure. Test it again. I'm going to make a setup.py to make this install-able with pip

**Comment by abdulla-alajmi** [comment]
@Julioocz still yours is not working but I have made some changes and now it's working fine

thank you

**Comment by Julioocz** [comment]
You can always comment the PR @abdulla-alajmi

**Comment by abdulla-alajmi** [comment]
@Julioocz  I really want to work with others to develop programs, but to be honest I don't know how to use github!

**Comment by LevPasha** [comment]
Wait for somone tests.

**Comment by LevPasha** [comment]
Plz make new pull request. Thx!

**Pull request closed without merging**
