### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by Ledokol**

### CODE REVIEW

**Comment by LevPasha** [comment]
@Ledokol add it to readme.

**Comment by bgokden** [comment]
requirements.txt has some unnecessary dependencies ( like kivy ) am I wrong?

**Comment by Ledokol** [comment]
@bgokden You are right, it seems like @dsouzarc generated requirements with all packages installed in single python distribution oh his computer.  Check out PEP 496 and virtualenv.

**Comment by LevPasha** [comment]
@Ledokol i think too...

**Comment by dsouzarc** [comment]
@bgokden  Just following up to confirm: `requirements.txt` has some unnecessary dependencies because of the way I installed it (as @Ledokol pointed out). 

I should have used a separate virtualenv for this project and then run that command to install only the essential libraries.

**Pull request closed without merging**
