### PR TITLE
Story feature (photo/video)

### PR DESCRIPTION
**Pull request by 01E0E1**

### CODE REVIEW

**Comment by Daedra223** [comment]
Hello, I tried your code:

```
if (api.login()):
    api.getSelfUserFeed()  # get self user feed
    print(api.LastJson)  # print last response JSON
    print("Login succes!")
    photo_path = 'test.jpg'
    InstagramAPI.uploadStoryPhoto(api,photo_path)

else:
    print("Can't login!")
```

But got that error:
Traceback (most recent call last):
  File "C:/Users/Waldemar/Desktop/Projekte/Test Projekt Story /examples/test.py", line 14, in <module>
    InstagramAPI.uploadStoryPhoto(api,photo_path)
  File "C:\Users\Waldemar\Desktop\Projekte\Test Projekt Story \InstagramAPI\InstagramAPI.py", line 286, in uploadStoryPhoto
    return self.uploadPhoto(photo, is_story=True)
  File "C:\Users\Waldemar\Desktop\Projekte\Test Projekt Story \InstagramAPI\InstagramAPI.py", line 162, in uploadPhoto
    if self.configure(upload_id, photo, caption, is_story=is_story) and not is_story:
  File "C:\Users\Waldemar\Desktop\Projekte\Test Projekt Story Jodel 3\InstagramAPI\InstagramAPI.py", line 529, in configure
    return self._sendRequest('media/configure_to_story/?', self.generateSignature(data))
AttributeError: 'InstagramAPI' object has no attribute '_sendRequest'

**Comment by LevPasha** [comment]
Guys, we need to test it. Thank you!

**Comment by Perados** [comment]
@01E0E1 It would be awesome if we could have the caption, hashtags and reel mentions for stories. Something like this: https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php, but the reel mention is missing there.

🙏

**Comment by alexshavelev44** [comment]
@linneudm hm don't see this method in repo https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py

**Pull request closed without merging**
