### PR TITLE
Fix __init__.py so that the package will be importable after installation

### PR DESCRIPTION
**Pull request by Perados**

### CODE REVIEW

**Comment by Perados** [comment]
@LevPasha I added a commit to fix a typo that was raising an exception.

**Comment by alittera** [comment]
It works

**Comment by Perados** [comment]
@LevPasha @xecgr  I don't understand why you decided to go with this https://github.com/LevPasha/Instagram-API-python/commit/c7ea8df73a36934af337ddf2c3ab776ccbb6e3df (putting everything inside the __init__.py is a bad practice) instead of merging this pr that was solving the issue in a clean way.

**Comment by xecgr** [comment]
If code remains in InstagramAPI.py the way to import without errors is this:
```
from InstagramAPI import InstagramAPI
username,password = "",""
api = InstagramAPI.InstagramAPI(username,password)
```
To much verbose and unlogical way to use it.
Perhaps is a bad practice put all code in `__init__.py` but for the most users of this lib (not all of them are developers) the best way to import is this one:
```
from InstagramAPI import InstagramAPI
username,password = "",""
api = InstagramAPI(username,password)
```
Cleaner and simple way to use. Several issues were opened due this two lines (and all examples uses this syntax)

**Comment by Perados** [comment]
@xecgr The whole purpose of doing `from InstagramAPI import InstagramAPI` inside the \_\_init\_\_.py file is that you won't have to do `InstagramAPI.InstagramAPI(username,password)` anywhere else anymore AND you will keep a nice structure. Take a look at my fork: https://github.com/Perados/Instagram-API-python, it works exactly the way you describe it. I use it like this in my projects:

```
from InstagramAPI import InstagramAPI
username,password = "",""
api = InstagramAPI(username,password)
```

**Pull request closed without merging**
