### PR TITLE
getLikedMedia now can get more than 20 media s...

### PR DESCRIPTION
**Pull request by ahmdrz**

### CODE REVIEW

**Comment by LevPasha** [comment]
@ahmdrz hi! Thx for your work. You test it? All work well?

**Comment by ahmdrz** [comment]
@LevPasha Hello my friend.
Yes i try it.
My test code is :
```python
import os
import sys
import json

from insta import Instagram

if os.path.exists('config.json'):
    with open('config.json') as data_file:    
        config = json.load(data_file)
else:    
    print 'configuration file not found'
    sys.exit(-1)
    
print 'connecting to instagram'
insta = Instagram(config["username"],config["password"])
if insta.login() == False:
    print 'instagram connection failed'
    sys.exit(-2)
    
print 'connected to instagram, getting data...'

insta.getHashtagFeed('tehran')

print insta.LastJson
```

and the result is :
```
{u'ranked_items': [{u'code': u'BJ8QW2_jo0q', u'next_max_id': 17852003434116181, u'max_num_visible_preview_comments': 2, u'like_count': 23316, u'image_versions2': {u'candidates': [{u'url': u'http://igcdn-photos-d-a.akamaihd.net/hphotos-ak-xpl1/t51.2885-15/e35/14145468_317144941952643_1589631836_n.jpg?se=7&ig_cache_key=MTMzMjAxMTUyOTQxNTg1NTQwMg%3D%3D.2', u'width': 1080, u'height': 945}, {u'url': u'http://igcdn-photos-d-a.akamaihd.net/hphotos-ak-xpl1/t51.2885-15/s750x750/sh0.08/e35/14145468_317144941952643_1589631836_n.jpg?ig_cache_key=MTMzMjAxMTUyOTQxNTg1NTQwMg%3D%3D.2', u'width': 750, u'height': 656}, {u'url': u'http://igcdn-photos-d-a.akamaihd.net/hphotos-ak ......................
```

And about getLikedMedia i wrote this code :

Test file :
```python
liked = insta.getTotalLikedMedia(5)
```

Instagram file:
```python
def getTotalLikedMedia(self,scan_rate = 1):
        next_id = ''
        liked_items = []
        for x in range(0,scan_rate):
            temp = self.getLikedMedia(next_id)
            next_id = temp["next_max_id"]
            for item in temp["items"]:
                liked_items.append(item)
        return liked_items
```

I will commit my `getTotalLikedMedia` method.

**Comment by LevPasha** [comment]
You finish your pull?

**Comment by ahmdrz** [comment]
Yes. I will commit more codes later.

**Comment by LevPasha** [comment]
@ahmdrz add to readmy info about your function plz!

**Pull request merged**
