### PR TITLE
adding function for solve two factor authentication

### PR DESCRIPTION
**Pull request by stezarpriansya**
Adding function for account that have two factor authentication

### CODE REVIEW

**Comment by stezarpriansya** [comment]
`finishTwoFactorAuth(verification_code, two_factor_identifier)`
`verification_code` : obtained from text messages
`two_factor_identifier` : obtained from error messages

**Comment by joshuachinemezu** [comment]
Nice one @stezarpriansya, tried using your method logging in with two factor authentication but I am having issues, Please can you help me with a guide on how to implement this. Thanks in anticipation for a positive response

**Comment by kantorjedi** [comment]
Thanks for the solution!

**Comment by stezarpriansya** [comment]
> Nice one @stezarpriansya, tried using your method logging in with two factor authentication but I am having issues, Please can you help me with a guide on how to implement this. Thanks in anticipation for a positive response

i'm sorry for my late reply. are you still having this issues?

**Comment by stezarpriansya** [comment]
> Thanks for the solution!

you're welcome 👍

**Comment by stezarpriansya** [comment]
> Thanks for the solution!
you're welcome

**Comment by joshuachinemezu** [comment]
@stezarpriansya ... Yes I am still having this issue

**Comment by stezarpriansya** [comment]
> @stezarpriansya ... Yes I am still having this issue

you just doing login as usual, like
`API = InstagramAPI(username, password)`
`API.login()`

then, when you've two factor auth, the request return error, and has a messages like this:
`Request return 400 error!
Two Factor Authentication Required!
Two Factor Identifier:  your_two_factor_identifier
Finish login with finishTwoFactorAuth(verification_code, two_factor_identifier) !`

its means that your verification code already sent to yor phone and you have to finish your login with this syntax:
`API.finishTwoFactorAuth(verification_code, two_factor_identifier)`

**Comment by Hattshire** [comment]
Is the issue also happening in my pull? 
#404

**Comment by joshuachinemezu** [comment]
@stezarpriansya Thanks very much, I really appreciate

**Comment by stezarpriansya** [comment]
> Is the issue also happening in my pull?
> #404

Right! but i dont know how, i cannot reopen my pull request. bcs accidentally i've closed this pull request :(

**Comment by stezarpriansya** [comment]
> @stezarpriansya Thanks very much, I really appreciate

You're Welcome 👍

**Comment by raghuvelagala** [comment]
@stezarpriansya Tried using your 2fa solution but I get a 'Request 400 error!' after call to finishTwoFactorAuth(). I modified test.py as such https://pastebin.com/HhyVptAG.  I do get the sms code.

Can you see anything I'm doing wrong? Can anyone confirm this is still working? I can still login normally through browser with 2fa.

**Comment by stezarpriansya** [comment]
> @stezarpriansya
> Tried using your 2fa solution but I get a 'Request 400 error!' after call to finishTwoFactorAuth(). I modified test.py as such https://pastebin.com/4u2NbKR0. I do get the sms code. I do not add a space within the code when passing to the func, i.e. "XXXXXX" and not "XXX XXX" as given by the sms.
> 
> Can you see anything I'm doing wrong? Can anyone confirm this is still working? I can still login normally through browser with 2fa.
> 
> P.S
> Also, I'm fairly new to this can you guide me on how you found out what params and values are required for different get/post requests to the API. How you went about finding out and testing it. I don't think this is documented anywhere right? for this unofficial api. I am also trying to solve a different problem (see 'checkpoint_challenge_required' issue when 2fa is disabled) which seems can be solved in a similar way.

Sorry for my late reply. I think you did it well, but i still try to understand why your problem occured. Can you attach your error messages?

**Pull request closed without merging**
