### PR TITLE
now uploadPhoto return success result with media object

### PR DESCRIPTION
**Pull request by dE1l**
{
  "status":"ok",
  "media": { media object } ,
  "upload_id" : "2683192367879012"
}
and PEP8 python style improved

### CODE REVIEW

**Comment by LevPasha** [comment]
Someone test it?

**Comment by ahmdrz** [comment]
All lines has been changed , new spaces ! I think it will be better if just the main reason change.
I think your IDE is change all of codes

**Comment by LevPasha** [comment]
@ahmdrz pep8...

**Comment by ahmdrz** [comment]
I'm not good python developer and I didn't hear pep8. Now I know it... 
It's good , perfect...
But lasjson will fill in sendrequest

**Comment by LevPasha** [comment]
@ahmdrz lets listen what @dE1l say.

**Comment by dE1l** [comment]
@LevPasha say about what?)

in this pull request i add only 2 lines:
```
         response = self.s.post(self.API_URL + "upload/photo/", data=m.to_string())
          if response.status_code == 200:
              if self.configure(upload_id, photo, caption):
 +                LastJson = self.LastJson
                  self.expose()
 +                return LastJson
          return False
```
You don't have return for success result and uploadPhoto() always return False.
Of Course i tested this.

All other changes automated refactor to PEP8 in last PyCharm. I'm every day using this function and it did not let me down.

**Comment by ahmdrz** [comment]
It's ok .

But its better to be :

```python
         response = self.s.post(self.API_URL + "upload/photo/", data=m.to_string())
          if response.status_code == 200:
              if self.configure(upload_id, photo, caption):
 +                LastJson = self.LastJson
                   self.expose()
                   self.LastJson = LastJson
 +                return True
          return False
```

**Comment by LevPasha** [comment]
@dE1l ok. PLZ make `return True` and resolve conflict. And i merge it.

**Comment by LevPasha** [comment]
Plz make new pull. Thx!

**Comment by joaopio** [comment]
I'm confused as to if this merge went through. When i use uploadPhoto I always get False, even when it is successful. Am i missing something?

**Pull request closed without merging**
