### PR TITLE
Added sleep before configuring video for Instagram to process it.

### PR DESCRIPTION
**Pull request by HDSant0s**

### CODE REVIEW

**Comment by LevPasha** [comment]
@HDSant0s are you sure we need it?

**Comment by HDSant0s** [comment]
Pretty sure, without the delay it returned error 202: _Transcode not finished yet_. It also depends on the video size, as some videos worked without it. Maybe a delay based on file size could be implemented...

**Comment by LevPasha** [comment]
@HDSant0s maybe you can write requests loop, that will recheck each 3-5 sec? If we get 202, wait a little and try again, before we get success.

**Comment by HDSant0s** [comment]
I'll get on to that!

**Pull request closed without merging**
